import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: 24,
    backgroundColor: "#151518",
  },
  loginBox: {
    flexDirection: "row",
    backgroundColor: "#212121",
    borderRadius: 16,
    padding: 24,
    width: "70%",
    height: "70%",
    shadowColor: "#000",
    shadowOpacity: 0.3,
    shadowOffset: { width: 0, height: 4 },
    shadowRadius: 8,
    elevation: 6,
  },
  loginBoxMobile: {
    backgroundColor: "#212121",
    borderRadius: 16,
    padding: 24,
    width: "90%",
    height: "40%",
    shadowColor: "#000",
    shadowOpacity: 0.3,
    shadowOffset: { width: 0, height: 4 },
    shadowRadius: 8,
    elevation: 6,
    alignItems: "center",
    justifyContent: "center",
  },
  leftSection: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingRight: 20,
    borderRightWidth: 1,
    borderRightColor: "#444",
  },
  logo: {
    width: "80%",
    height: "80%",
    marginBottom: 16,
  },
  logoMobile: {
    width: "40%",
    height: "40%",
    marginBottom: 0,
  },
  rightSection: {
    flex: 1,
    paddingLeft: 20,
    justifyContent: "center",
    alignItems: "center",
  },
  title: {
    color: "#fff",
    fontSize: 32,
    fontWeight: "bold",
    marginBottom: 32,
  },
  input: {
    width: "90%",
    backgroundColor: "#333",
    color: "#fff",
    padding: 12,
    borderRadius: 8,
    marginBottom: 16,
  },
  inputMobile: {
    width: "100%",
    backgroundColor: "#333",
    color: "#fff",
    padding: 12,
    borderRadius: 8,
    marginBottom: 16,
  },

  button: {
    backgroundColor: "#a11a1a",
    borderRadius: 8,
    paddingVertical: 14,
    paddingHorizontal: 0,
    marginTop: 8,
    height: "11%",
    width: "26%",
    alignItems: "center",
  },
  buttonMobile: {
    backgroundColor: "#a11a1a",
    borderRadius: 8,
    paddingVertical: 6,
    paddingHorizontal: 0,
    marginTop: 8,
    height: 42,
    width: "45%",
    alignItems: "center",
    justifyContent: "center",
  },
  buttonText: {
    color: "#fff",
    fontWeight: "bold",
    fontSize: 18,
  },
  error: {
    color: "#ff6b6b",
    marginBottom: 8,
    textAlign: "center",
  },
  linkBtn: {
    marginTop: 16,
  },
  linkText: {
    color: "#fff",
    textDecorationLine: "underline",
    fontSize: 16,
  },
});

export default styles;
